# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graphics-ColorNames-WWW
version:      0.01
version_from: WWW.pm
installdirs:  site
requires:
    Graphics::ColorNames:          0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
